export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  SIGNUP: "/signup",
  VERIFY_EMAIL: "/verify-email",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  EVENTS: "/events",
  EVENT_DETAIL: (id: string) => `/events/${id}`,
  EVENT_REGISTER: (id: string) => `/events/${id}/register`,
  NEWS: "/news",
  NEWS_DETAIL: (id: string) => `/news/${id}`,
  GALLERY: "/gallery",
  CONTACT: "/contact",
  MY_REGISTRATIONS: "/my-registrations",
  PROFILE: "/profile",
  ADMIN: "/admin",
  ADMIN_EVENTS: "/admin/events",
  ADMIN_EVENTS_CREATE: "/admin/events/create",
  ADMIN_EVENTS_EDIT: (id: string) => `/admin/events/${id}/edit`,
  ADMIN_EVENT_WORKSPACE: (id: string) => `/admin/events/${id}`,
  ADMIN_REGISTRATIONS: "/admin/registrations",
  ADMIN_CHECKINS: "/admin/check-ins",
  ADMIN_REVIEWS: "/admin/reviews",
  ADMIN_NEWS: "/admin/news",
  ADMIN_USERS: "/admin/users",
  ADMIN_ANALYTICS: "/admin/analytics",
  ADMIN_SETTINGS: "/admin/settings",
  ADMIN_PROFILE: "/admin/profile",
} as const;

export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: "/api/auth/v1/login",
    SIGNUP: "/api/auth/v1/signup",
    LOGOUT: "/api/auth/v1/logout",
    REFRESH_TOKEN: "/api/auth/v1/refresh-token",
    VERIFY_EMAIL: "/api/auth/v1/verify-email",
    RESEND_VERIFICATION: "/api/auth/v1/resend-email-verification",
    ME: "/api/auth/v1/me",
    FORGOT_PASSWORD: "/api/auth/v1/forgot-password",
    RESET_PASSWORD: "/api/auth/v1/reset-password",
    CHANGE_PASSWORD: "/api/auth/v1/change-password",
    UPDATE_PROFILE: "/api/auth/v1/update-profile",
    GOOGLE_LOGIN: "/api/auth/v1/google-login",
  },
  CONTACT: {
    SEND: "/api/contact/v1/send",
  },
  REVIEWS: {
    CREATE: "/api/reviews/v1/create",
  },
  EVENTS: {
    LIST: "/api/events/v1/all",
    GET: (id: string) => `/api/events/v1/${id}`,
    REVIEWS: (id: string) => `/api/events/v1/${id}/reviews`,
    CREATE: "/api/events/v1/create",
    UPDATE: "/api/events/v1/update",
    DELETE: "/api/events/v1/delete",
  },
  NEWS: {
    LIST: "/api/news/v1/all",
    GET: (id: string) => `/api/news/v1/${id}`,
    CREATE: "/api/news/v1/create",
    UPDATE: "/api/news/v1/update",
    DELETE: "/api/news/v1/delete",
  },
  REGISTRATIONS: {
    REGISTER: "/api/registrations/v1/register",
    CANCEL: "/api/registrations/v1/cancel",
    BY_USER: (userId: string) => `/api/registrations/v1/user/${userId}`,
    BY_EVENT: (eventId: string) => `/api/registrations/v1/event/${eventId}`,
  },
  ADMIN: {
    REGISTRATIONS: "/api/admin/v1/registrations",
    REGISTRATION_STATUS: (id: string) => `/api/admin/v1/registrations/${id}/status`,
    CHECKIN_EVENTS: "/api/admin/v1/checkins/events",
    CHECKIN_EVENT: (id: string) => `/api/admin/v1/checkins/events/${id}`,
    CHECKIN: (id: string) => `/api/admin/v1/checkins/${id}`,
    REVIEWS: "/api/admin/v1/reviews",
    REVIEW_STATUS: (id: string) => `/api/admin/v1/reviews/${id}/status`,
    REVIEW_REPLY: (id: string) => `/api/admin/v1/reviews/${id}/reply`,
    USERS: "/api/admin/v1/users",
    USER_DETAIL: (id: string) => `/api/admin/v1/users/${id}`,
    USER_ROLE: (id: string) => `/api/admin/v1/users/${id}/role`,
    USER_VERIFY: (id: string) => `/api/admin/v1/users/${id}/verify`,
    USER_SUSPEND: (id: string) => `/api/admin/v1/users/${id}/suspend`,
    USER_DELETE: (id: string) => `/api/admin/v1/users/${id}`,
    ANALYTICS: "/api/admin/v1/analytics/overview",
    DASHBOARD_STATS: "/api/admin/v1/dashboard/stats",
    DASHBOARD_REG_TREND: "/api/admin/v1/dashboard/registration-trend",
    DASHBOARD_REG_STATUS: "/api/admin/v1/dashboard/registration-status",
    DASHBOARD_ATTENDANCE: "/api/admin/v1/dashboard/attendance-trend",
    DASHBOARD_CATEGORIES: "/api/admin/v1/dashboard/top-categories",
    DASHBOARD_UPCOMING: "/api/admin/v1/dashboard/upcoming-events",
    DASHBOARD_RECENT: "/api/admin/v1/dashboard/recent-registrations",
    DASHBOARD_TOP: "/api/admin/v1/dashboard/top-events",
    EVENT_PARTICIPANTS: (id: string) => `/api/admin/v1/events/${id}/participants`,
    EVENT_REVIEWS: (id: string) => `/api/admin/v1/events/${id}/reviews`,
    NEWS: "/api/news/v1/all",
  },
} as const;
